export { ContentPanelSwitch } from './ContentPanelSwitch'
export { RightPanelSwitch } from './RightPanelSwitch'
export { ProjectPanelSwitch } from './ProjectPanelSwitch'
export { PerspectivePanelSwitch } from './PerspectivePanelSwitch'
export { ActionPanelSwitch } from './ActionPanelSwitch'
